Repository fga-eps-mds/2023-1-Alectrion-UserAPI, pull requests merged in 2023-06, with the labels that each got.

#10 126 tela cadastro usuario
  src/db/entities/user.ts
  src/db/migrations/1664151582109-default.ts
  src/db/migrations/1664151733139-create-users.ts
  src/domain/entities/user.ts
  src/presentation/controller/createUserController.spec.ts
  src/presentation/controller/createUserController.ts
  src/repository/protocol/repository.ts
  src/repository/userRepository.ts
  src/useCase/authenticationUser/authenticationUserUseCase.spec.ts
  src/useCase/createUser/createUserUseCase.spec.ts
  src/useCase/createUser/createUserUseCase.ts
  src/useCase/deleteUser/deleteUserUseCase.spec.ts
  src/useCase/getUser/getUserUseCase.spec.ts
Labels: US, EASY, MDS

#9 136 alterar senha de login
  .env.example
  package.json
  src/adapters/mailerAdapter.spec.ts
  src/adapters/mailerAdapter.ts
  src/db/entities/user.ts
  src/db/migrations/1664151582109-default.ts
  src/domain/entities/user.ts
  src/factories/controllers/recoverUserPassword.ts
  src/factories/useCases/recoverUserPassword.ts
  src/presentation/controller/recoverUserPasswordController.spec.ts
  src/presentation/controller/recoverUserPasswordController.ts
  src/routes.ts
  src/services/mailer.ts
  src/useCase/authenticationUser/authenticationUserUseCase.spec.ts
  src/useCase/createUser/createUserUseCase.spec.ts
  src/useCase/deleteUser/deleteUserUseCase.spec.ts
  src/useCase/getUser/getUserUseCase.spec.ts
  src/useCase/recoverUserPassword/recoverUserPasswordUseCase.spec.ts
  src/useCase/recoverUserPassword/recoverUserPasswordUseCase.ts
  src/useCase/updateUser/updateUserUseCase.ts
  yarn.lock
Labels: FEATURE, EASY, MDS, MINOR RELEASE

#11 127 visualizar perfil usuario
  .DS_Store
  db.env.example
  src/factories/controllers/authenticateUser.ts
  src/factories/controllers/updatePassword.ts
  src/factories/useCases/updatePassword.ts
  src/presentation/controller/authenticateUserController.spec.ts
  src/presentation/controller/authenticateUserController.ts
  src/presentation/controller/updatePasswordController.ts
  src/repository/userRepository.ts
  src/routes.ts
  src/useCase/authenticationUser/authenticationUserUseCase.spec.ts
  src/useCase/authenticationUser/authenticationUserUseCase.ts
  src/useCase/getUser/getUserUseCase.ts
  src/useCase/updatePassword/updatePasswordUseCase.ts
Labels: FEATURE, MEDIUM, MDS, MAJOR RELEASE

#13 fix: env
  db.env.example
Labels: FIX RELEASE
