Repository fga-eps-mds/2023-1-Alectrion-UserAPI, pull requests merged in 2023-07, with the labels that each got.

#20 #162 feat: Adicionando testes
  src/factories/controllers/controllers.spec.ts
  src/factories/useCases/authenticateUser.spec.ts
  src/factories/useCases/createUser.spec.ts
  src/factories/useCases/deleteUser.spec.ts
  src/factories/useCases/getUser.spec.ts
  src/factories/useCases/recoverUserPassword.spec.ts
  src/factories/useCases/updatePassword.spec.ts
  src/factories/useCases/updateUser.spec.ts
  src/repository/userRepository.spec.ts
Labels: MDS

#19 161 fix usuario deletado
  src/presentation/controller/authenticateUserController.spec.ts
  src/presentation/controller/authenticateUserController.ts
  src/repository/userRepository.ts
  src/useCase/authenticationUser/authenticationUserUseCase.spec.ts
  src/useCase/authenticationUser/authenticationUserUseCase.ts
Labels: MAJOR RELEASE

#21 162 aumentando cobertura
  src/presentation/controller/updatePasswordController.spec.ts
  src/useCase/updatePassword/updatePasswordUseCase.spec.ts
Labels: FIX RELEASE
